[package]
name = "camtcsv"
version = "0.0.1"
authors = ["Andreas Pfeil <der.anderas.pfeil@googlemail.com>"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
csv = "1.0.0"
serde = "1.0.70"
serde_derive = "1.0.70"
